name: Build
on: [push]
jobs:
  
  # BUILD
  build:
    name: Convert to HTML and PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: build_outputs
          # images_dir: docs/images
          # for example <img src="./images/file-name.png">
          # image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_pdf: true
          build_html: true
          table_of_contents: true
          template: docs/template.html

      - name: Rename HTML file to index.html
        run: |
          sudo mv build_outputs/fsharp-cheatsheet.html build_outputs/index.html || echo "File not found, no rename needed"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build_outputs/

  # DEPLOY
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4